# Generated by Django 2.1.8 on 2019-05-16 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagefrom', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
